# Generated by Django 2.2.9 on 2020-01-20 20:19

from django.db import migrations, models
import django.db.models.deletion
import homes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='Stores the two letter "Alpha-2" country code', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(choices=[('SqFt', 'Square Feet'), ('SqFt', 'Square Meters')], default='SqFt', max_length=4)),
                ('home_size', models.PositiveIntegerField(blank=True, null=True)),
                ('property_size', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(validators=[homes.validators.validate_year])),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('last_sold_price', models.PositiveIntegerField(blank=True, null=True)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True)),
                ('zestimate_amount', models.PositiveIntegerField()),
                ('zestimate_last_updated', models.DateField()),
                ('rentzestimate_amount', models.PositiveIntegerField()),
                ('rentzestimate_last_updated', models.DateField()),
                ('tax_value', models.PositiveIntegerField()),
                ('tax_year', models.PositiveSmallIntegerField(validators=[homes.validators.validate_year])),
                ('zillow_id', models.PositiveIntegerField()),
                ('link', models.URLField(help_text='Link to Zillow ad', max_length=500)),
                ('home_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.HomeType')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.State')),
            ],
        ),
    ]
