# Generated by Django 2.2.9 on 2020-01-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
