# Generated by Django 2.2.9 on 2020-01-20 22:45

from django.db import migrations, models
import homes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20200120_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rentzestimate_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='rentzestimate_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[homes.validators.validate_year]),
        ),
    ]
