# Generated by Django 2.2.9 on 2020-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20200120_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='zestimate_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
