# Generated by Django 2.2.9 on 2020-01-20 22:55

from django.db import migrations, models
import homes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_auto_20200120_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('SqFt', 'Square Feet'), ('SqFt', 'Square Meters')], default='SqFt', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='link',
            field=models.URLField(blank=True, help_text='Link to Zillow ad', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='tax_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='tax_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[homes.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='home',
            name='zestimate_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='zillow_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
